name: docs

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: Windows
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        run: |
          Get-Location
          ..\.venv\Scripts\Activate.ps1
          pip install --force-reinstall -r ..\requirements.txt
      - name: Build docs
        run: |
          sphinx-build docs-src docs
