name: Publish to PyPi

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
      - name: Update build tools
        run: |
          py -m pip install -U pip
          py -m pip install -U setuptools wheel twine
      - name: Build and publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          py setup.py sdist bdist_wheel
          py -m twine upload dist/*
