name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: Windows
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        run: |
          py -m venv --clear ..\.venv
          ..\.venv\Scripts\Activate.ps1
          pip install -r ..\requirements.txt
      - name: Build docs
        run: |
          sphinx-build docs-src docs
